export const FETCH_DATA = 'FETCH_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const EDIT_CLICKED = 'EDIT_CLICKED';
export const EDIT_MULTIPLE_CLICKED = 'EDIT_MULTIPLE_CLICKED';
export const SUBMIT_EDIT = 'SUBMIT_EDIT';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const CHANGE_CHECKBOX_STATUS = 'CHANGE_CHECKBOX_STATUS';

export const FETCH_EMPLOYEE_DATA = 'FETCH_EMPLOYEE_DATA';
export const DELETE_EMPLOYEE_DATA = 'DELETE_EMPLOYEE_DATA';
export const EDIT_EMPLOYEE_DATA = 'EDIT_EMPLOYEE_DATA';
export const SUBMIT_EDIT_EMPLOYEE_DATA = 'SUBMIT_EDIT_EMPLOYEE_DATA';
export const CANCEL_EDIT_EMPLOYEE_DATA = 'CANCEL_EDIT_EMPLOYEE_DATA';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const DISPLAY_ERROR = 'DISPLAY ERROR';
